/run/initialize
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 2703.2 mm
/gps/ang/type iso
/gps/ene/type Mono
/gps/ene/mono 1.9 MeV

# Set the output filename to contain the simulated energy in a uniform number format and disable appendage of additional file IDs
/utr/setUseFilenameID False
/utr/appendZerosToVar E 2 1.9
/utr/setFilename Efficiency_1900_keV_Zero

# Run the simulation
# /run/beamOn 100000000
/run/beamOn 10000000
