/run/initialize
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. mmp
/gps/ang/type iso
/gps/ene/type Mono
/gps/ene/mono 5.1 MeV

# Set the output filename to contain the simulated energy in a uniform number format and disable appendage of additional file IDs
/utr/setUseFilenameID False
/utr/appendZerosToVar E 2 5.1
/utr/setFilename Efficiency_5100_keV

# Run the simulation
/run/beamOn 100000000
