/run/initialize
/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0. 0.  2693.2 mm #at 5cm away
/gps/ang/type iso
/gps/ene/type Mono
/gps/ene/mono 0.6 MeV

# Set the output filename to contain the simulated energy in a uniform number format and disable appendage of additional file IDs
/utr/setUseFilenameID False
/utr/appendZerosToVar E 2 0.6
/utr/setFilename Efficiency_600_keV_Zero

# Run the simulation
# /run/beamOn 100000000
/run/beamOn 10000000
