/run/initialize
/ang/particle geantino
#/ang/particle gamma
/ang/energy 3.0 MeV  

/ang/nstates 3
/ang/state1 0.
/ang/state2 -1.
/ang/state3 2.

/ang/delta12 0.
/ang/delta23 0.

/ang/sourceX 0. mm
/ang/sourceY 0. mm
/ang/sourceZ 0. mm

/ang/sourceDX 1.0 mm
/ang/sourceDY 1.0 mm
/ang/sourceDZ 1.0 mm

/ang/sourcePV source
/ang/polarized true

/utr/setFilename AngularDist_Geanito_0_-1_2_testD
#/utr/setFilename  sphere_0_-1_2_

#/run/printProgress 100000
/run/beamOn 1000000
